export const gasMarkets = [
  { key: 'canada', label: 'Canada average' },
  { key: 'st_johns', label: "St. John's, NL" },
  { key: 'pei', label: 'Charlottetown and Summerside, PE' },
  { key: 'halifax', label: 'Halifax, NS' },
  { key: 'saint_john', label: 'Saint John, NB' },
  { key: 'quebec_city', label: 'Quebec City, QC' },
  { key: 'montreal', label: 'Montreal, QC' },
  { key: 'ottawa_gatineau', label: 'Ottawa-Gatineau' },
  { key: 'toronto', label: 'Toronto, ON' },
  { key: 'thunder_bay', label: 'Thunder Bay, ON' },
  { key: 'winnipeg', label: 'Winnipeg, MB' },
  { key: 'regina', label: 'Regina, SK' },
  { key: 'saskatoon', label: 'Saskatoon, SK' },
  { key: 'edmonton', label: 'Edmonton, AB' },
  { key: 'calgary', label: 'Calgary, AB' },
  { key: 'vancouver', label: 'Vancouver, BC' },
  { key: 'victoria', label: 'Victoria, BC' },
  { key: 'whitehorse', label: 'Whitehorse, YT' },
  { key: 'yellowknife', label: 'Yellowknife, NT' },
] as const;
